import { Inter } from 'next/font/google'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'blogs',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const header = (
    <header>
      <div>
        <h1>Navbar Hoga yaha</h1>
        <br />
      </div>
    </header>
  );

  const footer = (
    <footer>
      <div>
        <br />
        <h3>Footer hoga yaha</h3>
      </div>
    </footer>
  );

  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        {header}
        {children}
        {footer}
        </body>
    </html>
  )
}
